name: Update Profile Stats

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Allow the workflow to write to repository contents

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update commit count
      run: |
        # Simple, professional update
        echo "<!-- Profile updated: $(date) -->" >> README.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update profile stats"
          git push